In [3]:
import pandas as pd
import numpy as np
import math
import operator

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

# Exploratory Data Analysis

In [4]:
from sklearn import datasets
iris = datasets.load_iris()

#convert sklearn dataset to pandas dataframe
def sklearn_to_df(sklearn_dataset):
    df = pd.DataFrame(sklearn_dataset.data, columns=sklearn_dataset.feature_names)
    df['target'] = pd.Series(sklearn_dataset.target)
    return df

df = sklearn_to_df(datasets.load_iris())

len(df) #number of records

#iris = df
# print("First five rows")
# print(iris.head())
# print("*********")
# print("columns",iris.columns)
# print("*********")
# print("shape:",iris.shape)
# print("*********")
# print("Size:",iris.size)
# print("*********")
# print("no of samples available for each type")
# print(iris['target'].value_counts())
# print("*********")
# print(iris.describe())
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

# Training & Test Sets

In [10]:
'''
The data set consists of 50 samples from each of three species of Iris
Iris setosa,
Iris virginica and
Iris versicolor.
Four features were measured from each sample: the length and the width of the sepals and petals, in centimetres.
'''


#load dataset
iris = datasets.load_iris()
#load data
iris_data = iris.data
#load targets
iris_labels = iris.target

np.random.seed(42)
#split data randomly
#outputs randomly permuted array of indices equal to number of records
indices = np.random.permutation(len(iris_data))

#estimated k value for KNN algorithm
k_value = math.ceil(math.sqrt(len(iris_data)))
print(k_value)

n_samples = 12

X = iris_data
y = iris_labels

#https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle = False,test_size=0.3) 
print("total train: ", len(X_train), 
      '\n', X_train, y_train)
print("total tests: ", len(X_test),
      '\n', X_test, y_test)
print(type(y_train))
y_train.shape

13
total train:  105 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.

(105,)

# Parameter Optimisation

In [11]:
k_range = list(range(1, 31))
print("k_range: ", k_range)

classifier = KNeighborsClassifier()

param_grid = dict(n_neighbors=k_range)
print("param_grid: ", param_grid)

grid = GridSearchCV(classifier, param_grid, cv=10, scoring='accuracy')

grid.fit(X,y)
print("best_estimator: ", grid.best_estimator_)

k_range:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
param_grid:  {'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]}
best_estimator:  KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=13, p=2,
                     weights='uniform')


# KNN Algorithm

In [12]:
#Function calculates euclidean distance between two n-dimensional data instances 
def euclideanDistance(instance1, instance2):
    #handles if instances are lists or tuples:
    instance1 = np.array(instance1) 
    instance2 = np.array(instance2)
    
    '''
    https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html
    uses 2-norm frobenius norm and returns euclidean distance
    '''
    return np.linalg.norm(instance1 - instance2) #euclidean distance
print(X_train[2], X_test[2])
print(euclideanDistance(X_train[2], X_test[2]))

[4.7 3.2 1.3 0.2] [7.3 2.9 6.3 1.8]
5.866003750424985


In [13]:
#Function finds nearest neighbours; nearest -> smallest euclidean distance
def get_neighbors(training_set, 
                  labels, 
                  test_instance, 
                  k, 
                  distance=euclideanDistance):
    """
    get_neighbors calculates a list of the k nearest neighbors
    of an instance 'test_instance'.
    The list neighbors contains 3-tuples with  
    (index, dist, label)
    where
    index    is the index from the training_set, 
    dist     is the distance between the test_instance and the 
             instance training_set[index]
    distance is a reference to a function used to calculate the 
             distances
    """
    distances = [] #empty distance array
    
    #calculates euclidean distance between test_instance and ALL other instances in training_set
    for index in range(len(training_set)):
        dist = euclideanDistance(test_instance, training_set[index])
        distances.append((training_set[index], dist, labels[index]))
    distances.sort(key=lambda x: x[1])
    neighbors = distances[:k]
    return neighbors # The list neighbors contains 3-tuples with (index, dist, label)

In [113]:
# TEST OUTPUT

outArray = []
for i in range(n_samples):
    neighbors = get_neighbors(X_train, 
                              y_train, 
                              X_test[i], 
                              k_value, 
                              distance=euclideanDistance)
#     print(i,
#           X_test[i],
#           y_test[i],
#           neighbors)
    
    outArray.append([i,
          X_test[i],
          y_test[i],
          neighbors])

out_df = pd.DataFrame(outArray, columns=['i', 'X_test', 'y_test', 'neighbours'])
out_df.head()
# out_df.tail()

i                X_test  y_test  \
0  0  [7.6, 3.0, 6.6, 2.1]       2   
1  1  [4.9, 2.5, 4.5, 1.7]       2   
2  2  [7.3, 2.9, 6.3, 1.8]       2   
3  3  [6.7, 2.5, 5.8, 1.8]       2   
4  4  [7.2, 3.6, 6.1, 2.5]       2   

                                          neighbours  
0  [([7.1, 3.0, 5.9, 2.1], 0.8602325267042621, 2)...  
1  [([5.4, 3.0, 4.5, 1.5], 0.7348469228349535, 1)...  
2  [([7.1, 3.0, 5.9, 2.1], 0.5477225575051659, 2)...  
3  [([6.3, 2.9, 5.6, 1.8], 0.6000000000000002, 2)...  
4  [([7.1, 3.0, 5.9, 2.1], 0.7549834435270749, 2)...

In [14]:
from collections import Counter

#Function enables voting mechanic in KNN for Classification according to majority class vote
def vote(neighbors):
    class_counter = Counter() #A Counter is a dict subclass for counting hashable objects. 
    for neighbor in neighbors:
        class_counter[neighbor[2]] += 1 #neighbor[2] -> label for neighbor(s)
    return class_counter.most_common(1)[0][0]

In [15]:
for i in range(n_samples):
    neighbors = get_neighbors(X_train, 
                              y_train, 
                              X_test[i], 
                              k_value, 
                              distance=euclideanDistance)
    print("index: ", i, 
          ", result of vote: ", vote(neighbors), 
          ", label: ", y_train[i], 
          ", data: ", X_train[i])

index:  0 , result of vote:  1 , label:  0 , data:  [5.1 3.5 1.4 0.2]
index:  1 , result of vote:  1 , label:  0 , data:  [4.9 3.  1.4 0.2]
index:  2 , result of vote:  1 , label:  0 , data:  [4.7 3.2 1.3 0.2]
index:  3 , result of vote:  1 , label:  0 , data:  [4.6 3.1 1.5 0.2]
index:  4 , result of vote:  1 , label:  0 , data:  [5.  3.6 1.4 0.2]
index:  5 , result of vote:  1 , label:  0 , data:  [5.4 3.9 1.7 0.4]
index:  6 , result of vote:  1 , label:  0 , data:  [4.6 3.4 1.4 0.3]
index:  7 , result of vote:  1 , label:  0 , data:  [5.  3.4 1.5 0.2]
index:  8 , result of vote:  1 , label:  0 , data:  [4.4 2.9 1.4 0.2]
index:  9 , result of vote:  1 , label:  0 , data:  [4.9 3.1 1.5 0.1]
index:  10 , result of vote:  1 , label:  0 , data:  [5.4 3.7 1.5 0.2]
index:  11 , result of vote:  1 , label:  0 , data:  [4.8 3.4 1.6 0.2]


In [16]:
#Function returns vote 'probability' - i.e. distribution/percentage majority vote
def vote_prob(neighbors):
    class_counter = Counter() # Counter object - https://docs.python.org/2/library/collections.html
    for neighbor in neighbors:
        class_counter[neighbor[2]] += 1 #add to count of target (class)
        
    # aggregates into tuples ~ zip(*iterables), 
    # Return a list of the n most common elements and their counts from the most common to the least.    
    labels, votes = zip(*class_counter.most_common()) #returns list of sorted most common [labels], [votes]
    #print("L|V: ", labels, votes)
    #print("Class Counter: ", class_counter.most_common)
    winner = class_counter.most_common(1)[0][0]       #majority label
    votes4winner = class_counter.most_common(1)[0][1] #majority vote count
    return winner, votes4winner/sum(votes)            #returns majority label, majority proportion

In [117]:
for i in range(n_samples):
    neighbors = get_neighbors(X_train, 
                              y_train, 
                              X_test[i], 
                              k_value, 
                              distance=euclideanDistance)
    print("index: ", i, 
          ", result of vote: ", vote(neighbors), 
          ", vote_prob: ", vote_prob(neighbors), 
          ", label: ", y_test[i], "prediction: "
        "CORRECT" if (vote(neighbors) == y_test[i]) else "WRONG"
          ", data: ", X_test[i])

index:  0 , result of vote:  1 , vote_prob:  (1, 0.6153846153846154) , label:  2 WRONG, data:  [7.6 3.  6.6 2.1]
index:  1 , result of vote:  1 , vote_prob:  (1, 1.0) , label:  2 WRONG, data:  [4.9 2.5 4.5 1.7]
index:  2 , result of vote:  1 , vote_prob:  (1, 0.6923076923076923) , label:  2 WRONG, data:  [7.3 2.9 6.3 1.8]
index:  3 , result of vote:  1 , vote_prob:  (1, 0.6153846153846154) , label:  2 WRONG, data:  [6.7 2.5 5.8 1.8]
index:  4 , result of vote:  1 , vote_prob:  (1, 0.6153846153846154) , label:  2 WRONG, data:  [7.2 3.6 6.1 2.5]
index:  5 , result of vote:  1 , vote_prob:  (1, 0.7692307692307693) , label:  2 WRONG, data:  [6.5 3.2 5.1 2. ]
index:  6 , result of vote:  1 , vote_prob:  (1, 0.7692307692307693) , label:  2 WRONG, data:  [6.4 2.7 5.3 1.9]
index:  7 , result of vote:  1 , vote_prob:  (1, 0.6153846153846154) , label:  2 WRONG, data:  [6.8 3.  5.5 2.1]
index:  8 , result of vote:  1 , vote_prob:  (1, 0.8461538461538461) , label:  2 WRONG, data:  [5.7 2.5 5.  2. 

# Weighted KNN

In [17]:
#Function for weighted KNN voting mechanic; harmonic weights based on ranking of datapoint (vote += 1/rank)
def vote_harmonic_weights(neighbors, all_results=True):
    class_counter = Counter()
    number_of_neighbors = len(neighbors)
    for index in range(number_of_neighbors):
        #weighted count of votes
#         print("Index: ", index)
#         print(class_counter[neighbors[index][2]])
#         print(index, index+1, '\n')
        class_counter[neighbors[index][2]] += ( 1/(index+1) ) #add (1/ neighbour_rank) for each vote; index+1 = neighbour_rank
    labels, votes = zip(*class_counter.most_common())
    #print(labels, votes)
    winner = class_counter.most_common(1)[0][0]
    votes4winner = class_counter.most_common(1)[0][1]
    if all_results:
        total = sum(class_counter.values(), 0.0)
        
        for key in class_counter:
             class_counter[key] /= total #returns vote proportion for key ("class") in class_counter
        return winner, class_counter.most_common()
    else:
        return winner, votes4winner / sum(votes)

In [119]:
for i in range(n_training_samples):
    neighbors = get_neighbors(X_train, 
                              y_train, 
                              X_test[i], 
                              k_value, 
                              distance=euclideanDistance)
    print("index:", i, 
          ",result of vote: ", 
          vote_harmonic_weights(neighbors,
                                all_results=True), 
          ",label: ", y_test[i], 
        ",prediction: ",
        "CORRECT" if ( vote_harmonic_weights(neighbors,
                                all_results=True)[0] == y_test[i]) else "WRONG")

index: 0 ,result of vote:  (2, [(2, 0.6792973430029677), (1, 0.32070265699703226)]) ,label:  2 ,prediction:  CORRECT
index: 1 ,result of vote:  (1, [(1, 1.0)]) ,label:  2 ,prediction:  WRONG
index: 2 ,result of vote:  (2, [(2, 0.6551087135785297), (1, 0.3448912864214703)]) ,label:  2 ,prediction:  CORRECT
index: 3 ,result of vote:  (2, [(2, 0.6428800175917304), (1, 0.3571199824082695)]) ,label:  2 ,prediction:  CORRECT
index: 4 ,result of vote:  (2, [(2, 0.6792973430029677), (1, 0.32070265699703226)]) ,label:  2 ,prediction:  CORRECT
index: 5 ,result of vote:  (1, [(1, 0.8240565169246236), (2, 0.17594348307537655)]) ,label:  2 ,prediction:  WRONG
index: 6 ,result of vote:  (1, [(1, 0.5702486838924844), (2, 0.4297513161075155)]) ,label:  2 ,prediction:  WRONG
index: 7 ,result of vote:  (2, [(2, 0.6530929944598266), (1, 0.3469070055401734)]) ,label:  2 ,prediction:  CORRECT
index: 8 ,result of vote:  (1, [(1, 0.6569612554352426), (2, 0.34303874456475736)]) ,label:  2 ,prediction:  WRONG


# Distance Weighted KNN

In [18]:
#Function for distance weighted KNN voting mechanic; weight based on euclidean distance (vote += 1/distance)
def vote_distance_weights(neighbors, all_results=True):
    class_counter = Counter()
    number_of_neighbors = len(neighbors)
    for index in range(number_of_neighbors):
        dist = neighbors[index][1]
        print("neighbour_distance: ", dist)
        label = neighbors[index][2]
        class_counter[label] += (1 / (dist)) #sensitivity of distance weight can be adjusted here.
    labels, votes = zip(*class_counter.most_common())
    #print(labels, votes)
    winner = class_counter.most_common(1)[0][0]
    votes4winner = class_counter.most_common(1)[0][1]
    if all_results:
        total = sum(class_counter.values(), 0.0)
        for key in class_counter:
             class_counter[key] /= total
        return winner, class_counter.most_common()
    else:
        return winner, votes4winner / sum(votes)

In [121]:
for i in range(n_samples):
    neighbors = get_neighbors(X_test, 
                              y_test, 
                              X_train[i], 
                              k_value, 
                              distance=euclideanDistance)
    print("index: ", i, 
          ", result of vote: ", vote_distance_weights(neighbors,
                                                      all_results=True),
        ",label: ", y_test[i], 
        ",prediction: ",
        "CORRECT" if ( vote_harmonic_weights(neighbors,
                                all_results=True)[0] == y_test[i]) else "WRONG")

neighbour_distance:  3.591656999213594
neighbour_distance:  3.8961519477556315
neighbour_distance:  3.9774363602702683
neighbour_distance:  4.007492981902776
neighbour_distance:  4.028647415696738
neighbour_distance:  4.109744517606904
neighbour_distance:  4.1400483088968905
neighbour_distance:  4.141255848169732
neighbour_distance:  4.160528812542944
neighbour_distance:  4.190465367951393
neighbour_distance:  4.208325082500163
neighbour_distance:  4.27668095606862
neighbour_distance:  4.356604182158392
index:  0 , result of vote:  (2, [(2, 1.0)]) ,label:  2 ,prediction:  CORRECT
neighbour_distance:  3.479942528261063
neighbour_distance:  3.9153543900903784
neighbour_distance:  3.9812058474788765
neighbour_distance:  4.0024992192379
neighbour_distance:  4.031128874149275
neighbour_distance:  4.06201920231798
neighbour_distance:  4.106093033529563
neighbour_distance:  4.134005321718878
neighbour_distance:  4.153311931459037
neighbour_distance:  4.168932717135165
neighbour_distance:  4.1